# Please; update to last JeKa version
jeka.version=0.11.65
jeka.java.version=25

# Allow command-line shortcut as `jeka build` instead of `jeka project: build`
jeka.kbean.default=project

# Necessary to build runnable application jar
@project.pack.jarType=FAT
@project.pack.mainClass=app.Application

# Include ErrorProne/NullAway compile-processor
@project.compilation.compilerOptions=-XDcompilePolicy=simple \
  --should-stop=ifError=FLOW \
  "-Xplugin:ErrorProne -Xep:NullAway:ERROR -XepOpt:NullAway:AnnotatedPackages=app"
