# Please; update to last JeKa version
jeka.version=0.11.65
jeka.java.version=25

# Allow command-line shortcut as `jeka build` instead of `jeka project: build`
jeka.kbean.default=project

@project.pack.jarType=FAT
@project.pack.mainClass=org.example.Application

@project.compilation.fork=true
@project.compilation.compilerOptions=-XDcompilePolicy=simple \
  --should-stop=ifError=FLOW \
  "-Xplugin:ErrorProne -Xep:NullAway:ERROR -XepOpt:NullAway:AnnotatedPackages=org.example" \
  -Amicronaut.processing.group=org.example \
  -Amicronaut.processing.module=micronaut-demo1-application

